/*
 * This file is generated by jOOQ.
 */
package com.tech.biran.br.common.log.db;


import com.tech.biran.br.common.log.db.tables.SysLog;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.sys_log</code>.
     */
    public static final SysLog SYS_LOG = SysLog.SYS_LOG;
}
